name: Publish Bicep Module
on:
  workflow_call:
    secrets:
      azure-client-id:
        description: Azure Client ID to be used to authenticate to Azure
        required: true
      azure-subscription-id:
        description: Azure Subscription GUID authenticate
        required: true
      azure-tenant-id:
        description: Tenant ID used for Azure authentication scenario
        required: true
    inputs:
      bicep-file-path:
        required: true
        type: string
        description:  Path for the bicep file that needs to be published as module.
      registry-name:
        required: true
        type: string
        description: Name of the container registry where the bicep modules will be published
      registry-path:
        required: true
        type: string
        description: Path for the bicep module within the container registry from which it can be consumed


permissions:
  contents: read
  id-token: write

jobs:
  # Job only runs when a PR raises
  publish-module:
    # Job only runs when changes are pushed to main branch.
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
    - name: Login to Azure Cloud
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.azure-client-id }}
        tenant-id: ${{ secrets.azure-tenant-id }}
        subscription-id: ${{ secrets.azure-subscription-id }}
    - name: Lint module
      run: |
        echo "Restoring nested/child modules from private registry if any..."
        az bicep restore --file "${{ inputs.bicep-file-path }}/module.bicep" --force
        echo "Running linter on ${{ inputs.bicep-file-path }}/module.bicep..."
        az bicep lint --file "${{ inputs.bicep-file-path }}/module.bicep"
    - name: Run PSRule analysis
      uses: microsoft/ps-rule@latest
      with:
          inputType: inputPath
          inputPath: ${{ inputs.bicep-file-path }}
          baseline: 'Azure.All'
          modules: PSRule.Rules.Azure
          outcome: All
    - name: Publish module to ACR
      run: |
        echo "Publishing module ${{ inputs.registry-path }}..."
        az bicep publish --file "${{ inputs.bicep-file-path  }}/module.bicep" --target "br:${{ inputs.registry-name }}.azurecr.io/${{ inputs.registry-path }}" --with-source --force