name: Publish Entra ID Application module

on:
    workflow_dispatch:
#    pull_request:
#        branches:
#            - main
#        paths:
#            - 'EntraIDApplication/**'
#            - 'utilities.bicep'
#            - '.github/workflows/entraid-app.yml'
#    push:
#        branches:
#            - main
#        paths:
#            - 'EntraIDApplication**'
#            - 'utilities.bicep'
#            - '.github/workflows/entraid-app.yml'
jobs:
    key-vault:
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/bicep-publish.yml
        secrets:
            azure-client-id: ${{ secrets.ClIENT_ID }}
            azure-tenant-id: ${{ secrets.TENANT_ID }}
            azure-subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        with:
            bicep-file-path: EntraIDApplication
            registry-name: crmahi
            registry-path: entraid/app:1.0
