name: Publish Entra ID object retrieval module

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'EntraIDObjectRetrieve/**'
            - 'utilities.bicep'
jobs:
    key-vault:
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/bicep-publish.yml
        with:
            azure-client-id: 4efea1b2-111b-464b-aa2f-efa403e4c7d4
            bicep-file-path: ./EntraIDObjectRetrieve/module.bicep
            registry-name: mahicr
            registry-path: entraid/retrieve-object:1.0
