name: Publish Entra ID object retrieval module

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        paths:
            - 'EntraIDObjectRetrieve/**'
            - 'utilities.bicep'
    push:
        branches:
            - main
        paths:
            - 'EntraIDObjectRetrieve/**'
            - 'utilities.bicep'
jobs:
    key-vault:
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/bicep-publish.yml
        secrets:
            azure-client-id: ${{ secrets.ClIENT_ID }}
            azure-tenant-id: ${{ secrets.TENANT_ID }}
            azure-subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        with:
            bicep-file-path: ./EntraIDObjectRetrieve/
            registry-name: crmahi
            registry-path: entraid/get-object:1.0
