name: Publish Key Vault Bicep module

on:
    workflow_dispatch:
    pull_request:
        branches:
          - main
        paths:
            - 'KeyVault/**'
            - '.github/workflows/key-vault.yml'
            - 'PrivateEndpoint/module.bicep'
            - 'KeyVaultRBAC/module.bicep'
            - 'utilities.bicep'
    push:
        branches:
            - main
        paths:
            - 'KeyVault/**'
            - '.github/workflows/key-vault.yml'
            - 'PrivateEndpoint/module.bicep'
            - 'KeyVaultRBAC/module.bicep'
            - 'utilities.bicep'
jobs:
    key-vault:
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/bicep-publish.yml
        secrets:
            azure-client-id: ${{ secrets.ClIENT_ID }}
            azure-tenant-id: ${{ secrets.TENANT_ID }}
            azure-subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        with:
            bicep-file-path: ./KeyVault/
            registry-name: crmahi
            registry-path: key-vault/vault:1.0
