name: Publish Key Vault Bicep module

on:
    workflow_dispatch:
    #push:
    #    branches:
    #        - main
    #    paths:
    #        - 'KeyVault/**'
    #        - '.github/workflows/key-vault.yml'
    #        - 'PrivateEndpoint/module.bicep'
    #        - 'KeyVaultRBAC/module.bicep'
    #        - 'utilities.bicep'
jobs:
    key-vault:
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/bicep-publish.yml
        with:
            azure-client-id: 4efea1b2-111b-464b-aa2f-efa403e4c7d4
            bicep-file-path: ./KeyVault/module.bicep
            registry-name: mahicr
            registry-path: key-vault/vault:1.0
